-- SQL Server Script cho CSDL QueenBeautiful
CREATE DATABASE QueenBeautiful;
GO

USE QueenBeautiful;
GO

-- 1. DANH_MUC
CREATE TABLE DANH_MUC (
    DanhMucID INT IDENTITY(1,1) PRIMARY KEY,
    TenDanhMuc NVARCHAR(255),
    TrangThai BIT
);

-- 2. THUONG_HIEU
CREATE TABLE THUONG_HIEU (
    ThuongHieuID INT IDENTITY(1,1) PRIMARY KEY,
    TenThuongHieu NVARCHAR(255),
    TrangThaiHVT BIT
);

-- 3. SAN_PHAM
CREATE TABLE SAN_PHAM (
    SanPhamID INT IDENTITY(1,1) PRIMARY KEY,
    DanhMucID INT FOREIGN KEY REFERENCES DANH_MUC(DanhMucID),
    ThuongHieuID INT FOREIGN KEY REFERENCES THUONG_HIEU(ThuongHieuID),
    TenSP NVARCHAR(500),
    GiaBan DECIMAL(18,2),
    HoaHongCTV DECIMAL(18,2),
    HinhAnh VARCHAR(1000),
    ThanhPhan NVARCHAR(MAX),
    TinhChatDa NVARCHAR(255),
    TrangThai NVARCHAR(100)
);

-- 4. MA_KHUYEN_MAI
CREATE TABLE MA_KHUYEN_MAI (
    VoucherID INT IDENTITY(1,1) PRIMARY KEY,
    MaCode VARCHAR(50) UNIQUE,
    LoaiGiam NVARCHAR(50),
    GiaTriGiam DECIMAL(18,2),
    GiaTriToiDa DECIMAL(18,2),
    DieuKienDonToiThieu DECIMAL(18,2),
    NgayBatDau DATETIME,
    NgayKetThuc DATETIME,
    SoLuong INT,
    TrangThai BIT
);

-- 5. KHACH_HANG
CREATE TABLE KHACH_HANG (
    KhachHangID INT IDENTITY(1,1) PRIMARY KEY,
    MaKhachHang VARCHAR(100) UNIQUE,
    HoTen NVARCHAR(255),
    Sdt VARCHAR(20),
    Email VARCHAR(255),
    GoogleID VARCHAR(255),
    LoaiKhach NVARCHAR(50)
);

-- 6. NHAN_VIEN
CREATE TABLE NHAN_VIEN (
    NhanVienID INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(255),
    Sdt VARCHAR(20),
    Email VARCHAR(255),
    MatKhau VARCHAR(255),
    VaiTro NVARCHAR(50),
    TrangThai BIT
);

-- 7. CONG_TAC_VIEN
CREATE TABLE CONG_TAC_VIEN (
    CTVID INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(255),
    Sdt VARCHAR(20),
    Email VARCHAR(255),
    MatKhau VARCHAR(255),
    LinkMXH VARCHAR(500),
    SoTaiKhoan VARCHAR(50),
    NganHang NVARCHAR(255),
    MaGioiThieu VARCHAR(50) UNIQUE,
    SoDuVi DECIMAL(18,2),
    TongDoanhThu DECIMAL(18,2),
    TrangThaiPheDuyet NVARCHAR(50)
);

-- 8. LICH_SU_VI_CTV
CREATE TABLE LICH_SU_VI_CTV (
    LichSuViID INT IDENTITY(1,1) PRIMARY KEY,
    CTVID INT FOREIGN KEY REFERENCES CONG_TAC_VIEN(CTVID),
    LoaiGiaoDich NVARCHAR(100),
    SoTien DECIMAL(18,2),
    DonHangID INT,
    MoTa NVARCHAR(500),
    ThoiGian DATETIME
);

-- 9. YEU_CAU_RUT_TIEN
CREATE TABLE YEU_CAU_RUT_TIEN (
    RutTienID INT IDENTITY(1,1) PRIMARY KEY,
    MaGiaoDich VARCHAR(100) UNIQUE,
    CTVID INT FOREIGN KEY REFERENCES CONG_TAC_VIEN(CTVID),
    SoTienRut DECIMAL(18,2),
    NgayYeuCau DATETIME,
    NgayXuLy DATETIME,
    TrangThai NVARCHAR(50),
    GhiChu NVARCHAR(MAX)
);

-- 10. DON_HANG
CREATE TABLE DON_HANG (
    DonHangID INT IDENTITY(1,1) PRIMARY KEY,
    MaDonHang VARCHAR(100) UNIQUE,
    KhachHangID INT FOREIGN KEY REFERENCES KHACH_HANG(KhachHangID),
    NhanVienID INT NULL FOREIGN KEY REFERENCES NHAN_VIEN(NhanVienID),
    CTVID INT NULL FOREIGN KEY REFERENCES CONG_TAC_VIEN(CTVID),
    VoucherID INT NULL FOREIGN KEY REFERENCES MA_KHUYEN_MAI(VoucherID),
    NgayTao DATETIME,
    TongTien DECIMAL(18,2),
    TienHoaHong DECIMAL(18,2),
    PhuongThucThanhToan NVARCHAR(100),
    TrangThaiDon NVARCHAR(100)
);

ALTER TABLE LICH_SU_VI_CTV ADD CONSTRAINT FK_LICH_SU_VI_CTV_DONHANG FOREIGN KEY (DonHangID) REFERENCES DON_HANG(DonHangID);

-- 11. CHI_TIET_DON_HANG
CREATE TABLE CHI_TIET_DON_HANG (
    ChiTietDonHangID INT IDENTITY(1,1) PRIMARY KEY,
    DonHangID INT FOREIGN KEY REFERENCES DON_HANG(DonHangID),
    SanPhamID INT FOREIGN KEY REFERENCES SAN_PHAM(SanPhamID),
    SoLuong INT,
    DonGia DECIMAL(18,2)
);

-- 12. PHAN_HOI
CREATE TABLE PHAN_HOI (
    PhanHoiID INT IDENTITY(1,1) PRIMARY KEY,
    KhachHangID INT FOREIGN KEY REFERENCES KHACH_HANG(KhachHangID),
    SanPhamID INT FOREIGN KEY REFERENCES SAN_PHAM(SanPhamID),
    NoiDung NVARCHAR(MAX),
    DiemDanhGia INT
);

-- 13. NHA_CUNG_CAP
CREATE TABLE NHA_CUNG_CAP (
    NhaCungCapID INT IDENTITY(1,1) PRIMARY KEY,
    TenNhaCungCap NVARCHAR(255),
    Sdt VARCHAR(20),
    DiaChi NVARCHAR(MAX)
);

-- 14. KHO_TON_KHO
CREATE TABLE KHO_TON_KHO (
    KhoID INT IDENTITY(1,1) PRIMARY KEY,
    SanPhamID INT FOREIGN KEY REFERENCES SAN_PHAM(SanPhamID),
    SoLuongTon INT
);

-- 15. PHIEU_NHAP_KHO
CREATE TABLE PHIEU_NHAP_KHO (
    PhieuNhapID INT IDENTITY(1,1) PRIMARY KEY,
    NhaCungCapID INT FOREIGN KEY REFERENCES NHA_CUNG_CAP(NhaCungCapID),
    NhanVienID INT FOREIGN KEY REFERENCES NHAN_VIEN(NhanVienID),
    NgayNhap DATETIME,
    TongTien DECIMAL(18,2)
);

-- 16. CHI_TIET_PHIEU_NHAP
CREATE TABLE CHI_TIET_PHIEU_NHAP (
    ChiTietPhieuNhapID INT IDENTITY(1,1) PRIMARY KEY,
    PhieuNhapID INT FOREIGN KEY REFERENCES PHIEU_NHAP_KHO(PhieuNhapID),
    SanPhamID INT FOREIGN KEY REFERENCES SAN_PHAM(SanPhamID),
    SoLuong INT,
    GiaNhap DECIMAL(18,2)
);

-- 17. PHIEU_XUAT_KHO
CREATE TABLE PHIEU_XUAT_KHO (
    PhieuXuatID INT IDENTITY(1,1) PRIMARY KEY,
    NhanVienID INT FOREIGN KEY REFERENCES NHAN_VIEN(NhanVienID),
    NgayXuat DATETIME,
    LyDoXuat NVARCHAR(500)
);

-- 18. CHI_TIET_PHIEU_XUAT
CREATE TABLE CHI_TIET_PHIEU_XUAT (
    ChiTietPhieuXuatID INT IDENTITY(1,1) PRIMARY KEY,
    PhieuXuatID INT FOREIGN KEY REFERENCES PHIEU_XUAT_KHO(PhieuXuatID),
    SanPhamID INT FOREIGN KEY REFERENCES SAN_PHAM(SanPhamID),
    SoLuong INT
);

-- 19. PHIEU_KIEM_KE
CREATE TABLE PHIEU_KIEM_KE (
    PhieuKiemKeID INT IDENTITY(1,1) PRIMARY KEY,
    NhanVienID INT FOREIGN KEY REFERENCES NHAN_VIEN(NhanVienID),
    NgayKiemKe DATETIME,
    GhiChu NVARCHAR(MAX)
);

-- 20. HANG_LOI
CREATE TABLE HANG_LOI (
    HangLoiID INT IDENTITY(1,1) PRIMARY KEY,
    SanPhamID INT FOREIGN KEY REFERENCES SAN_PHAM(SanPhamID),
    NhanVienID INT FOREIGN KEY REFERENCES NHAN_VIEN(NhanVienID),
    SoLuong INT,
    PhanLoai NVARCHAR(255),
    HinhAnh VARCHAR(1000),
    DeXuatXuLy NVARCHAR(MAX),
    NgayBaoCao DATETIME
);
